### ISSUE TITLE
Refactor/relocate pages components into a pages folder.

### ISSUE THREAD

**Issue by JoeDravarol** [Together-100Devs/Together#202]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary
Refactor components related to LandingPage and CalendarPage into their own folder inside of a `pages` folder.
Create a `pages` folder to store components that are "page" specific. For example: **LandingPage** and **CalenderPage**. Then conditionally render those page in `App.js*. This would make the codebase more cleaner and easier to work with our current simple state routing. 

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git checkout -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### What you need to do
NOTE: Remember to follow **Creating your branch** instructions above before starting this series of steps.

<h2>Relocate CalenderPage component to pages folder</h2>

1. You first want to make sure you are on the new branch you have created. This new branch will be where you commit your work.
3. Create a `pages` folder within `client/src`.
4. Relocate/move the `client/src/features/home/CalendarPage.js` component into the newly created pages folder.
5. Fix any imports issue that you encounter.
6. Within `client/src/App.js` you want to **copy** the rejection modal code and paste it under line 23 so it will looks something like below:
```jsx
{
  isAuthenticated && (
    <h3>Hello, {auth.user.displayName}, welcome to Together!</h3>
  );
}
{
  isNot100Dever && (
    <Modal context={rejectionModalContext}>
      <RejectionModal handleClose={rejectionModalContext.handleClose} />
    </Modal>
  );
}
```
7. After that, you want to remove the same rejection modals code that is wrapped between the LandingPage component and CalendarPage component (**Important note**: you want to refactor CalendarPage component into a self-closing component). Example of what your App.js should look like after the changes:
```jsx
function App() {
  const routing = useRoutingContext();
  const auth = useAuthContext();
  const isAuthenticated = auth.isAuthenticated();
  const isNot100Dever = auth.isNot100Dever();
  //Sets rejection modal to true because updating state is a pain
  //Line 52 will prevent the modal from rendering unless user is not 100Dever
  const [rejectionModalOpen, setRejectionModalOpen] = useState(true);
  const rejectionModalContext = {
    isOpen: rejectionModalOpen,
    handleClose: () => {
      setRejectionModalOpen(false);
    },
  };

  return (
    <>
      {isAuthenticated && (
        <h3>Hello, {auth.user.displayName}, welcome to Together!</h3>
      )}
      {isNot100Dever && (
        <Modal context={rejectionModalContext}>
          <RejectionModal handleClose={rejectionModalContext.handleClose} />
        </Modal>
      )}
      {routing.currentPage === "landingPage" && (
        <div className="bg-primary flex justify-center">
          <div className="w-full tablet:w-11/12 desktop:w-2/3">
            <LandingPage />
          </div>
        </div>
      )}
      {routing.currentPage === "calendarPage" && <CalendarPage />}
    </>
  );
}
```

8. Start your server if you haven't with `npm run dev-concurrent`.
9. Make sure that everything is working as expected in your local host.
10. Add your changes with `git add . ` and create a new commit with a short/meaningful message of what you had done: `git commit -m "Your message"`

<h2>Your second commit - Relocate LandingPage component to pages folder</h2>

1. You want to complete this second task on the same branch you previously had worked on.
5. Relocate/move the `client/src/features/home/LandingPage.js` component into the newly created pages folder.
6. Fix any imports issue that you encounter.
12. You want to also copy the divs that is wrapping **LandingPage** component inside of `client/src/App.js` into `client/src/pages/LandingPage.js` (Note: Do not copy `<LandingPage />` you want to keep that in the `App.js`)

Example of the divs that should be copied into client/src/pages/LandingPage.js
```jsx
<div className="bg-primary flex justify-center">
  <div className="w-full tablet:w-11/12 desktop:w-2/3">
    <LandingPage />
  </div>
</div>
```

After the changes in `client/src/App.js`, the same section where you copied the divs from should look like this:
```jsx
  {routing.currentPage === "landingPage" && <LandingPage/>}
```

13. Make sure that everything is working as expected in your local host.
14. Follow `# When you are done` instructions to make your second & final PR.

#### This is what `client/src/App.js` will look like (Note: I have omitted imports and exports): 
```jsx
function App() {
  const routing = useRoutingContext();
  const auth = useAuthContext();
  const isAuthenticated = auth.isAuthenticated();
  const isNot100Dever = auth.isNot100Dever();
  //Sets rejection modal to true because updating state is a pain
  //Line 52 will prevent the modal from rendering unless user is not 100Dever
  const [rejectionModalOpen, setRejectionModalOpen] = useState(true);
  const rejectionModalContext = {
    isOpen: rejectionModalOpen,
    handleClose: () => {
      setRejectionModalOpen(false);
    },
  };

  return (
    <>
      {isAuthenticated && (
        <h3>Hello, {auth.user.displayName}, welcome to Together!</h3>
      )}
      {isNot100Dever && (
        <Modal context={rejectionModalContext}>
          <RejectionModal handleClose={rejectionModalContext.handleClose} />
        </Modal>
      )}
      {routing.currentPage === "landingPage" && <LandingPage />}
      {routing.currentPage === "calendarPage" && <CalendarPage />}
    </>
  );
}

```

#### This is what `client/src/pages/LandingPage.js` will look like:
```jsx
const LandingPage = () => {
  const cards = [
    {
      heading: "Join 100devs",
      description: (
        <>
          <a
            className="underline font-bold"
            href="https://leonnoel.com/100devs/"
          >
            100Devs
          </a>{" "}
          is a diverse and inclusive community of participants in a software
          engineering training program run by Leon Noel. It is 100% free and
          requires absolutely no previous technical experience.
        </>
      ),
    },
    {
      heading: "Contributing to Together",
      description:
        "We are currently working on video resources for individuals that would like to learn more about how to contribute to Together and how Together works. Follow along on our Youtube when it is ready!",
    },
    {
      heading: "Community Taught",
      description: (
        <>
          Keep track of your 100devs course progress using{" "}
          <a
            className="underline font-bold"
            href={`https://communitytaught.org/`}
          >
            Community Taught
          </a>{" "}
          created by 100devs alumna, Laura Abro.
          <br></br>
          <br></br>
          <a
            className="underline font-bold"
            href={`https://communitytaught.org/resources/`}
          >
            Additional Resources
          </a>
        </>
      ),
    },
  ];

  return (
    <div className="bg-primary flex justify-center">
      <div className="w-full tablet:w-11/12 desktop:w-2/3">
        <div className="flex flex-wrap desktop:w-full pt-20 tablet:pt-0">
          <HamburgerNav logo={"./logoicon.png"} logotext={"./logotext.png"} />
          <NavContainer />
          <LongCard
            img={"/Homeoffice.png"}
            heading="Welcome!"
            title="Together"
            description=" is a new app designed for
          100Devs. Together is a group calendar for public events, so you can
          see what's going on in your community. We're making it
          easier to find out about the events that are happening in Discord and
          let you know how much fun they'll be!"
          />
          <div className="w-full p-6 text-center tablet:inline-flex tablet:space-x-10 tablet:p-6 tablet:w-full tablet:h-[27rem]">
            {cards.map((cardData, index) => {
              return (
                <SmallCard
                  heading={cardData.heading}
                  description={cardData.description}
                  Icon={CgChevronDoubleRightO}
                  key={index}
                  index={index}
                />
              );
            })}
          </div>
          <BottomCard
            heading="Who we are"
            description={
              <>
                <p>
                  Together is a community-driven open source project backed by
                  members of 100devs. Together is not only designed to be a
                  valuable tool to the 100devs community but also provides an
                  additional opportunity for students to learn in a group
                  environment. Together is open to all varying skill sets and
                  encourages peer programming.
                </p>
                <p>
                  <br></br>
                  Interested in collaborating with us?{" "}
                  <a
                    className="underline font-bold"
                    href={`https://github.com/Caleb-Cohen/Together`}
                  >
                    <br></br>
                    Together GitHub
                  </a>
                </p>
              </>
            }
            img={"/threeHumans.png"}
          />
        </div>
      </div>
    </div>
  );
};

```

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or contact (put your name or contact info here).

### Relevant file locations
(One of the biggest barriers for new developers is navigating an unfamiliar codebase. Provide file directory paths to the files that the new developer will be coding in.)

## Potential Problems
(List any problems the new developer could run into.)

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by TrizzIzBizy** [comment]
I'd like to tackle this issue.  I'll ensure requirements are in place.

**Comment by Caleb-Cohen** [comment]
> I'd like to tackle this issue. I'll ensure requirements are in place.

All yours! @JoeDravarol how is this issue impacted by the current landing page and calendar page redesigns?
