### ISSUE TITLE
Create RSVP Module

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#211]
## Please provide a summary of the feature
This issue is for building the RSVP functionality of the events. 

This includes:
- Front-end RSVP button
- Placing event into user module
- Ability to RSVP for single events or all events

## Which Branch should this fix be Pulled into?
PR into Development. If working as a team, I can open a new branch for collaboration. 

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by itsdaijoebu** [comment]
I've just started poking around the codebase, but this seems like an interesting problem so I'm down to give this a shot.

**Comment by Caleb-Cohen** [comment]
> I've just started poking around the codebase, but this seems like an interesting issue so I'm down to give this a shot.

Hey there Joseph! I've assigned you.

I'm not totally satisfied with how I typed up this issue, would you have some time to jump on a call so we can make sure we're on the same page for this issue.

**Comment by Caleb-Cohen** [comment]
@itsdaijoebu I've added the tech spec template to discussions so it should be easier to submit whenever you're ready.

**Comment by Caleb-Cohen** [comment]
Hey there @itsdaijoebu just checking in on how you're doing!

**Comment by itsdaijoebu** [comment]
Hey, sorry! I got a bit sidetracked with some other stuff and haven't worked on this yet. I'm still interested in getting this done, though!

**Comment by Caleb-Cohen** [comment]
> Hey, sorry! I got a bit sidetracked with some other stuff and haven't worked on this yet. I'm still interested in getting this done, though!

Hey! Haven't heard back so unassigning for now. Let me know if you get interested in this again!

**Comment by Caleb-Cohen** [comment]
Closed/Lack of interest
