### ISSUE TITLE
Admin.js for Soft Security

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#213]
## Please provide a summary of the feature
Mario Recommended checking out Admin.JS for authorizing pending events. 

Functionality should include taking in events submitted trough the add event form and setting them to pending. Set events to approved and visualize only approved event.

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by InstincDev** [comment]
I am interested in taking lead on this issue.

**Comment by Caleb-Cohen** [comment]
> I am interested in taking lead on this issue.

All yours! When you get some time to take a look at this would you be able to give me an ETA on the project?

**Comment by DevRhyse** [comment]
I would like to help out on this issue if I could

**Comment by cblanken** [comment]
@Caleb-Cohen is the AdminJS library something we should keep in mind for the current Admin Dashboard, or was this idea abandoned?

**Comment by intelagense** [comment]
> @Caleb-Cohen is the AdminJS library something we should keep in mind for the current Admin Dashboard, or was this idea abandoned?

@cblanken this was explored, then abandoned. The bundle size was too large for our host plan so that's why we are making our own. I will close this and leave the link to the Admin Dash repo for future reference:
https://github.com/Together-100Devs/Together-Admin-Dash
