### ISSUE TITLE
Add a "Today" button that jumps to the current date/month 

### ISSUE THREAD

**Issue by isaaclee12** [Together-100Devs/Together#222]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

## Summary
Add a button that says something like "Today" or "Jump To Current Date" that brings the user back to the current month on the Calendar page.

You will also want to know the following React concepts if you want to take this on:

- React Hooks (useState, useEffect)
- React Functional Components

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git checkout -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or in this thread.

### Relevant file locations
Once you have cloned your fork of the repository into your IDE, navigate to ```client\src\features\calendar``` to see the Calendar files you'll likely be working with. You may also need to modify the useDate hook, which is located at ```client\src\hooks\useDate.js```

## Potential Problems
There are a couple of devs working on a re-design of the calendar page as listed in Issue #176 . It may be good to be in touch with those folks, although I don't forsee there being too much of an issue. The main focus here should be the implementation of a working button, i.e. functionality > aesthetics.

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MaViSunshine** [comment]
I would love to work on this issue

**Comment by Caleb-Cohen** [comment]
> I would love to work on this issue

It's yours! If you would like some advice with design @natashka333 can answer any questions.

**Comment by WonjaeSung** [comment]
Would love to tag along if it's not too late! @MaViSunshine

**Comment by Caleb-Cohen** [comment]
Hey, @MaViSunshine just checking in on this. Thank you!

**Comment by Caleb-Cohen** [comment]
Hey @MaViSunshine I'm going to go ahead and reassign this task to @WonjaeSung. I hope you're doing well!

**Comment by Caleb-Cohen** [comment]
Hey @WonjaeSung I'm checking in on this thank ya!

**Comment by Caleb-Cohen** [comment]
@WonjaeSung has requested to be removed from this issue and it is now open!

**Comment by soph-em** [comment]
hey, if this would be considered a good first issue then I'd be interested in giving it a go

**Comment by Caleb-Cohen** [comment]
> hey, if this would be considered a good first issue then I'd be interested in giving it a go

You're assigned!

**Comment by soph-em** [comment]
Hey, 

So I've got as far as adding button that does what it's supposed to, but wasn't sure how you wanted it to be styled. For now I found a placeholder icon - BsCalendarCheck, is there a preferred icon and tiptext that should go on this, as well as where it should be situated in the header? This is what I've currently got:
![Screenshot 2023-03-11 190207](https://user-images.githubusercontent.com/92051936/224509570-0fe4c0f5-fdb0-4333-877a-fc570c26f7d1.png)

**Comment by Natashka333** [comment]
Hi @soph-em , thanks for you contribution! I believe, we want to go with Text button. 
<img width="832" alt="Screenshot 2023-03-12 at 2 59 09 PM" src="https://user-images.githubusercontent.com/102708144/224570188-acc5a83d-c5ce-4bdc-9cd3-09bf2efd4b29.png">

**Comment by soph-em** [comment]
Thank you! I'll style it like that before submitting a PR
