### ISSUE TITLE
Modals not displaying for unauthenticated guest users/visitors.

### ISSUE THREAD

**Issue by intelagense** [Together-100Devs/Together#279]
## Describe the bug
Modals do not appear when users are not logged in.  

## To Reproduce
1. Make sure you are not logged in (i.e. log out)
2. Click to view Calender
3. Click on any event title or click `+` buttons to create a new event
4. Nothing happens

## Expected behavior
- When clicking an `event title`, the event details modal should show for guest users. 🚨 **(Discord user name and discriminator must be hidden from guest users for privacy and to prevent spam)** 🚨
- When clicking `add event`, a modal should pop up to tell the user that they cannot create events without logging in and should suggest signing up.

## Screenshots
N/A

## Which Branch should this fix be Pulled into?
PR into development

## Device Information
N/A

## Additional context
We may not want guest users to view full event details. In this case, the modal should still pop up with text explaining that the details are available to logged-in users. 

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by Caleb-Cohen** [comment]
To add on to this. The `+` should not work unless the user is logged in.

**Comment by romanstetsyk** [comment]
this is because the test user is not added to the database. I'll make a pr to address this

**Comment by Caleb-Cohen** [comment]
> this is because the test user is not added to the database. I'll make a pr to address this p.s. please disregard this. I misread guest users for test users. I'm going to create a new issue

If this is the case, why is this issue occurring in production where there is no test user?

**Comment by DevRhyse** [comment]
I would like to help out on this issue.

You mentioned this being spilt into two issues though. You're wanting this user to be able to view the events but with limited visibility?

**Comment by Caleb-Cohen** [comment]
> I would like to help out on this issue.
> 
> You mentioned this being spilt into two issues though. You're wanting this user to be able to view the events but with limited visibility?

This won't need to be split into two issues, but @intelagense wants non-logged-in users to not be able to see the authors of events. 

I'll ship you some times I plan to work on this, and when I say work on it, I mean stumble around and hope it works.

**Comment by DevRhyse** [comment]
> > I would like to help out on this issue.
> > You mentioned this being spilt into two issues though. You're wanting this user to be able to view the events but with limited visibility?
> 
> This won't need to be split into two issues, but @intelagense wants non-logged-in users to not be able to see the authors of events.
> 
> I'll ship you some times I plan to work on this, and when I say work on it, I mean stumble around and hope it works.

Awesome keep me posted and I'll be sure to make it!

**Comment by Caleb-Cohen** [comment]
@DevRhyse I'll be working on this around 6:30pm CST tonight.

**Comment by DevRhyse** [comment]
Hey, sorry I missed your message. I didn't read my emails or git
notifications until way later in the day.
