### ISSUE TITLE
Repo Weight-Loss

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#284]
## Please provide a summary of the feature

Cyclic has a limit of 250mb for builds. As it stands, we're at roughly 176mb, but I believe there are a few options available to us to explore to slim down the size and give us more clearance for future development. 

- Instead of importing the entire date-fns library, only import what we do.
- Investigate our dependencies and see if you can find anything not being used
- Check if tree shaking is functioning properly

## Are there any potential issues you foresee with this feature

Pretty easy to break the repo if you pull a required dependency. 

## Which Branch should this fix be Pulled into?
PR into Development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by TrizzIzBizy** [comment]
Very small observation.  Should Repo Wheight-Loss be Repo Weight-Loss?

**Comment by Caleb-Cohen** [comment]
> Very small observation. Should Repo Wheight-Loss be Repo Weight-Loss?
Yes 😂 thank you!

**Comment by RascalTwo** [comment]
Most significant contributor to the size is [`mongodb-memory-server`](https://github.com/nodkz/mongodb-memory-server), setting [`MONGOMS_DISABLE_POSTINSTALL`](https://github.com/nodkz/mongodb-memory-server/blob/master/docs/api/config-options.md#disable_postinstall) to a truthy in the environment variables page eliminates over half of the current bundle size - from `174.91 MB` to `67.42 MB`!

What this does is disables the [`postinstall`](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server/postinstall.js#L4-L7) script, which downloads an entire `mongodb` server instance binary - only used during development to allow developers to start developing without having to pass pre-existing MongoDB credentials to the application, and has no use during production.

**Comment by Caleb-Cohen** [comment]
> Most significant contributor to the size is [`mongodb-memory-server`](https://github.com/nodkz/mongodb-memory-server), setting [`MONGOMS_DISABLE_POSTINSTALL`](https://github.com/nodkz/mongodb-memory-server/blob/master/docs/api/config-options.md#disable_postinstall) to a truthy in the environment variables page eliminates over half of the current bundle size - from `174.91 MB` to `67.42 MB`!
> 
> What this does is disables the [`postinstall`](https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server/postinstall.js#L4-L7) script, which downloads an entire `mongodb` server instance binary - only used during development to allow developers to start developing without having to pass pre-existing MongoDB credentials to the application, and has no use during production.

Cool thank you I will get this implemented.

**Comment by Caleb-Cohen** [comment]
Reduced size to 61mb
