### ISSUE TITLE
Daylight Savings Time Bugs (THIS WAY LIES MANDESS)

### ISSUE THREAD

**Issue by isaaclee12** [Together-100Devs/Together#302]
## Background Info:

For more background on how bonkers this problem is, make sure to check out this video: https://www.youtube.com/watch?v=-5wpm-gesOY

To keep things concise, I will mostly be referring to the US/North American daylight savings time.

**Daylight Savings Time (DST) begins** in the US on Sunday, March 12, 2023, 2:00:00 am when clocks are turned *forward* 1 hour to Sunday, March 12, 2023, 3:00:00 am local daylight time.
- This causes the times from 2:00am-2:59am to be skipped, in other words they "don't exist"
- The user should not be able to input a time between 2:00am-2:59am on March 12, 2023, or any future days when DST begins.
- Calling the unix timestamp values for times within that range return the same timestamp as though the hour were 3am
- Example: 2:30AM is equal to 3:30AM on March 12, 2023
![image](https://user-images.githubusercontent.com/59675296/215360017-7b8979a2-bf7d-465d-8098-35a46aa56631.png)

**Daylight Savings Time (DST) ends** in the US on Sunday, November 5, 2023, 2:00:00 am when clocks are turned *backward* 1 hour to Sunday, November 5, 2023, 1:00:00 am local standard time.
- This causes the times from 1:00am-1:59am to occur **twice**.
- This can cause an event from 1:00am-2:00am to appear as a 2-hour long 1:00am-3:00am event in non-DST timezones.
- According to how Google and Apple calendar handle this, this seems to actually be the expected behaviorl
- Calling the unix timestamp values *seem* to be unaffected by this, though I could be entirely wrong on this.

## Expected behavior
- Submitted events should have the same durations across all recurrences, and across all timezones.
- Submitted events should start and end at valid times (e.g. times not skipped over by DST)
- Submitted events should (ideally) occur at the expected times

## Bug 1: Event time is within skipped hour on DST start date.

A bug occurs when the user is able to input a start or end time between 2:00AM and 2:59AM on March 12, 2023, when DST beings.

### To Reproduce the behavior:
1. If you're not already in a timezone that uses DST, switch your machine to such a timezone (mine is in "Eastern Standard Time"). The method for doing this will vary by machine.
2. Run Together locally
3. Enter some events that start and/or ends between 2:00AM-2:59AM inclusive on 03/12/2023 (See test cases for examples)
4. See how the event times break!
5. If you want to take it a step further, change your machine's timezone to one that doesn't use DST, and note the differences.

### Test cases:
```
// All events run from 3/10/23 to 4/10/23 and recur on Sat/Sun/Mon

DST Test 1 - 1:30AM-2:30AM
Expected behavior occurred.

DST Test 2 - 2AM - 3AM
Runtime error:
ValidationError: Event validation failed: endAt: should be greater than 'startAt' 
field
[dev] [1]     at model.Document.invalidate (C:\Users\isaac\Documents\[Coding Projects]\Together\node_modules\mongoose\lib\document.js:2782:32)
[dev] [1]     at C:\Users\isaac\Documents\[Coding Projects]\Together\node_modules\mongoose\lib\document.js:2574:17
[dev] [1]     at C:\Users\isaac\Documents\[Coding Projects]\Together\node_modules\mongoose\lib\schematype.js:1273:9
[dev] [1]     at processTicksAndRejections (node:internal/process/task_queues:78:11)        
[dev] [1] POST /events/ 500 23.974 ms - 84

DST Test 3 - Start 2AM, End 2:30AM
Possible Logic Error: Start time of 2AM leaps to 3AM ONLY on March 12

DST Test 4 - Start 2:30AM, End 2:45AM
Possible Logic Error: Start time of 2:30AM leaps to 3:30AM ONLY on March 12

DST Test 5 - Start 2:45AM, End 3:00AM
DEFINITE Logic Error: Start time of 2:45AM leaps to 3:45AM on March 12
This causes the event time to run frmo 3:45AM-3:00AM, which is impossible
Therefore, if the start time is offset by DST
And the end time is NOT offset by DST
then the end time should also be offset

DST Test 6 - Start 3:00AM, End 4:00AM
Expected behavior

DST Test 7 - Start 2:59AM, End 3:00AM
Same as Test 5, 3/12 time range is 3:59AM-3:00Am

Test 8 - Loading all these tests with the BROWSER
Set to "Asia/Shanghai" time, which does not use DST.
Logic errors still occurred.

Test 9 - Loading tests with MACHINE set to 
"China Standard Time", which does not use DST
AND no browser timezone override (browser inherits machine's time)
NO LOGIC ERRORS HERE
```
The times for 2:00AM through 2:59AM on March 12, 2023 *do not exist*. Therefore, **the user should not be allowed to input times during a time period that's skipped over when DST starts**.

One possible solution would be to check if the timestamp of a current datetime plus 60 minutes has the timestamp as the selected datetime, then force the selected datetime forward by 60 minutes. Using this, we can detect if a selected time is in a non-existent hour for ANY form of daylight savings time in the world that skips over an hour.

There is also one case for Lord Howe Island in Australia where only 30 minutes are skipped, but apparently no more than 400 people are ever on there. Given the scope of this project, it's probably not worth the headache to deal with this.

### Proposed Solution:
- If the start time of an event is within an hour skipped by the start of DST, then the start time (and the end time if one was selected) should be forced one hour forwards.
- If ONLY the end time of an event is within the skipped hour, then ONLY the end time should be forced forwards.
- pseudocode:
```js
if startTime.UTCtimestamp === (startTime + 60 min).UTCtimestamp {
    add 1 hour to startTime
    if endTime exists, also add 1 hour to endTime
} else if endTime.UTCtimestamp === (endTime+ 60 min).UTCtimestamp {
    add 1 hour to endTime
}
```
- This would prevent the user from submitting invalid times that are skipped over by DST.

## Bug 2: Events on days when DST ends may not follow expected behavior
When the user is able to inputs a start or end time between 1:00AM and 1:59AM on November 5, 2023, when DST ends.

### To Reproduce the behavior:
1. If you're not already in a timezone that uses DST, switch your machine to such a timezone (mine is in "Eastern Standard Time"). The method for doing this will vary by machine.
2. Run Together locally
3. Enter some events that start and/or ends between 1:00AM-1:59AM inclusive on 11/05/2023 (See test cases for examples)
4. See how the event times break!
5. If you want to take it a step further, change your machine's timezone to one that doesn't use DST, and note the differences.

### Test cases:
```
All tests are 11/3/23 - 12/3/23, Recurr. Sat/Sun/Mon 

DST End Test 1 - 12AM-1AM
Expected Behavior

DST End Test 2 - 12:30AM-1:30AM
Expected Behavior

DST End Test 3 - 1AM-2AM
Expected Behavior is DST timezones
NOTE: End time has an hour added in non-DST timezones,
time range is 1PM-3PM

DST End Test 4 - 1AM-1:30AM
Expected Behavior

DST End Test 5 - 1:15AM-1:45AM
Expected Behavior

DST End Test 6 - 1:30AM-2AM
Expected Behavior is DST timezones
NOTE: End time has an hour added in non-DST timezones,
time range is 1:30PM-3PM

DST End Test 7 - 1:30AM-2:30AM
Expected Behavior is DST timezones
NOTE: End time has an hour added in non-DST timezones,
time range is 1:30PM-3:30PM

DST End Test 8 - 2AM-3AM
Expected Behavior is DST timezones
NOTE: End time has an hour added in non-DST timezones,
time range is 3PM-4PM
```

### Proposed Solution:
- This behavior appears to match what Google and Apple Calendar do to handle this time discrepancy.
- Therefore, it may suffice to implement a warning that detects when the user is entering a start/end time within the hour when DST ends. I have no idea how we can detect this, as I can't figure out how to do so using UNIX timestamps.

## Bug 3: Recurring event times within the skipped DST-start hour behave incorrectly

To summarize, a start date will be pushed forward by an hour if it recurs during the skipped hour when DST starts, but the end date is not. This leads to a case where you could implement an event that regularly runs from 2:45am-3:00am, and that event ends up running from 3:45am-3:00am (which is impossible) on the DST start date:
![image](https://user-images.githubusercontent.com/59675296/215362190-d9b47296-5a44-42cd-9f33-fb13f5b45796.png)

### To reproduce:
1. If you're not already in a timezone that uses DST, switch your machine to such a timezone (mine is in "Eastern Standard Time"). The method for doing this will vary by machine.
2. Run Together locally
3. Enter an event that starts between 2:00AM-2:59AM inclusive and ends at 3:00AM or later on 03/12/2023
4. See how the event times break!
5. If you want to take it a step further, change your machine's timezone to one that doesn't use DST, and note the differences.

### Proposed solution:
- Save the intended duration of the event to the database
- Render the events on the calendar based on the startTime and duration so events always have the same duration
- Pseudocode:
```js
// On event submit:
duration = firstEventEnd - firstEventStart
event = { ..., duration}
DataService.create(event)

// On calendar render
events = DataService.getAll()
for each event in events {
   convert event.startTime to local time
   set event.endTime = event.startTime + duration
   render the event on the calendar
}
```

## It's possible there's a 4th bug when recurring event times cross the repeated DST-end hour, but this has yet to be tested.
- I'd appreciate it if someone could look into this. 

## Proposed Solutions Summarized:
- Prevent user from inputting times that would be skipped over by DST
- Show warning when a time to be submitted would cross one of the wacky DST hours
- Save the duration of submitted events to DB, and use that duration data to render events with consistent durations.

## Which Branch should this fix be Pulled into?
PR into ???

## Additional info
https://www.timeanddate.com/time/change/usa
https://en.wikipedia.org/wiki/Daylight_saving_time_by_country#Observance_as_of_2023
https://www.youtube.com/watch?v=-5wpm-gesOY

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by isaaclee12** [comment]
credit to @romanstetsyk for the proposed solutions to Bug 1 and Bug 3

**Comment by BigPugLabs** [comment]
A related bug so just adding it here, I'm in UK time and If I set a non-recurring event for 15th Feb, 23:30 until 16th Feb, 00:30 the front-end sends this
```
firstEventStart: 1676503800000, // Wed Feb 15 2023 23:30:00
firstEventEnd: 1676421000000,   // Wed Feb 15 2023 00:30:00
lastEventStart: 1676590200000   // Thu Feb 16 2023 23:30:00
```
Which fails validation due to <https://github.com/Caleb-Cohen/Together/blob/main/server/models/Event.js#L92> and firstEventEnd ends up before the start

This seems to happen on any date but would likely be fixed as part of the DST bug fix, Romans test branch seems to have replaced the front-end code which generates the timestamps

**Comment by Caleb-Cohen** [comment]
@romanstetsyk does #289 solve this?

**Comment by romanstetsyk** [comment]
It solves how the events are stored in the database but not how they are displayed.

**Comment by romanstetsyk** [comment]
What do you think would be a good solution to warn users about daylight saving time? Is a simple warning enough?
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25715951/220144565-24721c41-1761-466f-9bc4-357ef5f78305.png">

**Comment by Caleb-Cohen** [comment]
> What do you think would be a good solution to warn users about daylight saving time? Is a simple warning enough? <img alt="image" width="300" src="https://user-images.githubusercontent.com/25715951/220144565-24721c41-1761-466f-9bc4-357ef5f78305.png">

If I saw "Attention to Daylight Saving Time" I would say Ok, how should I react to that? Maybe some short instructions?

**Comment by romanstetsyk** [comment]
Do you have ideas of what can be written? This is for users to pay attention and not miss events. Because it can start an hour sooner or later than expected. There's no need for any particular action on the users' part.
To make it even more clear, we can include the event's duration in the modal.

**Comment by Caleb-Cohen** [comment]
> Do you have ideas of what can be written? This is for users to pay attention and not miss events. Because it can start an hour sooner or later than expected. There's no need for any particular action on the users' part. To make it even more clear, we can include the event's duration in the modal.

With your description, my recommendation would be to say, "Start or end time may be affected by timezone shifts."

**Comment by romanstetsyk** [comment]
<img width="300" display="inline" alt="image" src="https://user-images.githubusercontent.com/25715951/221207540-96edd33d-1539-4f6e-88eb-9045252cd1b8.png"> 
<img width="300" display="inline" alt="image" src="https://user-images.githubusercontent.com/25715951/221207655-85304ee7-8b93-4f55-b067-fb291f3d1333.png">

What do you think about adding timezone abbreviations? Disregard the CSS for now
