### ISSUE TITLE
Description field in the Add Event Form should be larger/paragraph size

### ISSUE THREAD

**Issue by isaaclee12** [Together-100Devs/Together#305]
### Intro
This issue has been opened specifically to give 100Devs members a chance to get involved. The issues presented will have more instruction and be easier to solve. If you are already contributing to this project or your skills are well-ahead of this issue, consider letting someone else take this on!

This is a relatively easy task, very good for anyone who wants to make their first Pull Request!

## Summary
The description entry box is too darn small!!!!!
<img width="271" alt="image" src="https://user-images.githubusercontent.com/59675296/215628751-b6b5de7d-1466-4983-81fc-c4f77b034490.png">
_absolutely microscopic._

It should be larger, like this description box in this other indie open source (/s) calendar app I found:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/59675296/215628839-670de2c9-db8a-4ae1-baf2-6cdc591d15c0.png">
_look at the size of that thing._

## The Task
Change the styling of the input field for the event description in client\src\features\form\FormCreateEvent.js to be larger.

### Creating your branch
- Fork the Together repository.
- Navigate to the development branch using `git checkout development`.
- Create a new branch using `git checkout -b your-branch-name-here`.
- If you have questions, more instructions about this can be found in our [contributing document.](https://github.com/CalebCohen/Together/blob/development/.github/CONTRIBUTING.md)

### Setting up a local server
- Execute `npm install`
- Execute `npm run dev-concurrent` in a vscode terminal.
- If you get errors, you may have to do one of the following:
- Delete your node_modules folder and then run `npm i`
- Make sure you have a .env file with the [necessary secrets](https://github.com/Caleb-Cohen/Together/wiki/02---Onboarding)

### When you are done
-Use `git add .` and then `git commit -m 'add a descriptive commit message here'` to commit your changes to your local branch.
-Push your commit(s) using `git push`.
-Open your fork in github and you will see a message saying you can create a pull request. Make sure your pull request is pulling into the 'development' branch instead of 'main'.

### Who to contact
If you have any questions, you can either send a message in the Together channel in 100Devs Discord or contact me @isaaclee12 

### Relevant file locations
The relevant file is in client\src\features\form\FormCreateEvent.js

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MikeJakuszewski** [comment]
Is it possible if I can have this assigned to me and tackle this problem?

**Comment by Caleb-Cohen** [comment]
> Is it possible if I can have this assigned to me and tackle this problem?

Done!

**Comment by MikeJakuszewski** [comment]
Awesome! Thank you

**Comment by Caleb-Cohen** [comment]
> Awesome! Thank you

Hey Mike, could I get an update on this? Thank you!

**Comment by MikeJakuszewski** [comment]
Hi Caleb, sorry I had a few personal matters come up. I will have time to work on this issue tomorrow. Sorry for the delay!

**Comment by MikeJakuszewski** [comment]
Hi Caleb, in making changes with the description box larger I had to change the element tag from input to textarea. This added multi-line functionality and allowed me to change the textbox to the desired size. However, after running the 'npm run test-frontend' command, it is showing errors with event creation as it cannot find the desired 'input' element. How would you like me to proceed?
