### ISSUE TITLE
Add event success form is displaying even if event was not successful. 

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#320]
## Describe the bug
Looks like some back-end validation rejections are not also caught on the front end. 

## To Reproduce
1. Go to Calendar Page
2. Click on Add event
3. Add a recurring event with a start date of today but a start time that has already passed. For example if it is 6pm local have the start time to be 5pm.
4. See error below
<img width="945" alt="Screenshot 2023-02-08 at 7 29 51 PM" src="https://user-images.githubusercontent.com/75268174/217692531-0df69805-ee90-45e3-8a49-744b16aafaad.png">

<img width="497" alt="Screenshot 2023-02-08 at 7 30 08 PM" src="https://user-images.githubusercontent.com/75268174/217692497-f6ae35b9-1059-44a0-9125-6fbbfe9ae136.png">

## Expected behavior
Front end should prevent user from getting to the point where they can submit an event that will be rejected OR the validation should be removed. I'd prefer former than the later on this one. 

## Which Branch should this fix be Pulled into?
PR into development

## Additional context

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by MatthewBozin** [comment]
Hey Caleb! Since I uncovered several bugs with the front-end form, I went ahead and recomposed this issue as #331, based around rebuilding the front-end form validation. I also listed the various bugs I ran into as possible examples of errors the rebuilt validation should be able to catch.

**Comment by Caleb-Cohen** [comment]
> Hey Caleb! Since I uncovered several bugs with the front-end form, I went ahead and recomposed this issue as #331, based around rebuilding the front-end form validation. I also listed the various bugs I ran into as possible examples of errors the rebuilt validation should be able to catch.

Ok I will close this issue.
