### ISSUE TITLE
Reimplement front-end form validation

### ISSUE THREAD

**Issue by MatthewBozin** [Together-100Devs/Together#331]
## Please provide a summary of the feature
Bug reports #328, #329, and #330 all have to do with front-end form validation, so this issue potentially covers them all.

Inactive front-end form validation code still exists in files like FormCreateEvent.js. If that code can be revived, then that's ideal, but writing new validation is fine.

- Reimplement the pre-existing front-end form validation (or build new validation), and update it to cover any type of invalid form data the user could send to the server. 
- Validation should display an error message to the user, and prevent the user from advancing the form until the inputted information is valid. 
- A good starting point would be the errors mentioned in the included bug reports, but there will most likely be others.

## Which Branch should this fix be Pulled into?
PR into development

*If you're interested in working on this feature, please comment so you can be assigned*

**Comment by gflacruz** [comment]
I can start working on this along with #328 #329 #330

**Comment by Caleb-Cohen** [comment]
> I can start working on this along with #328 #329 #330

Sounds good! Let us know if you'd to let someone else take any of them on!
