### ISSUE TITLE
Resizing components on landing/onboarding page

### ISSUE THREAD

**Issue by Natashka333** [Together-100Devs/Together#335]
I have created a wireframe for a screen size of 1280x832. I am sharing with Figma file where you can check the size of every component and the gaps between them. 

https://www.figma.com/file/7Yu0P8zeI9VhI8uFX078Je/Onboard-page-Together?node-id=0%3A1&t=c9fMs2qVZFnHZf5O-1

Here is what it looks like:
![Screen Shot 2023-02-16 at 5 44 46 PM](https://user-images.githubusercontent.com/102708144/219513184-c1239b6e-4906-484e-9957-d7764f3624a1.png)
![Screen Shot 2023-02-16 at 5 44 52 PM](https://user-images.githubusercontent.com/102708144/219513195-80877023-0a19-4ad7-b7dd-eb10433f3d79.png)

![Screen Shot 2023-02-16 at 5 44 14 PM](https://user-images.githubusercontent.com/102708144/219513095-089d18d5-b6d0-40a2-85ea-e2d9e0a06dec.png)

**Comment by Blake-Larson** [comment]
Hey, I would love to work on this issue!

**Comment by Blake-Larson** [comment]
@Natashka333 I have a question about the copy of the page. For example, the live version of the app has a button that has a discord logo and 'Login with Discord' but the figma file has 'Discord Login'. My question is, if I see differences in the text of the page, do you want me to use what is on the figma file or leave it as is and just change the layout?

**Comment by Natashka333** [comment]
> @Natashka333 I have a question about the copy of the page. For example, the live version of the app has a button that has a discord logo and 'Log in with Discord' but the Figma file has 'Discord Login'. My question is, if I see differences in the text of the page, do you want me to use what is on the figma file or leave it as is and just change the layout?

Hi, Blake. Welcome to the Together team😊. Good point. The text in figma is mostly the same as on the website. Let me make couple changes in Figma so the text is the same as on the website  which will be less confusion for you as well.

**Comment by Natashka333** [comment]
Also, we are getting rid of the buttons (**>>**) in sections. Basically, the sections have information purpose, but they don't take you to an other page. 
Let me know if you have any concerns,feedback or great points 😊

**Comment by Blake-Larson** [comment]
Sounds good about the buttons. I will let you know when I get closer to finishing to make sure I have it the way you want!

**Comment by Blake-Larson** [comment]
@Natashka333 I got some good work done on it today. Would you like to set up a meeting for next week where I can share my updates with you before I submit to github?

**Comment by Natashka333** [comment]
> @Natashka333 I got some good work done on it today. Would you like to set up a meeting for next week where I can share my updates with you before I submit to github?

Sure. Having a meeting works for me. Thank you!
