### ISSUE TITLE
Change the hex codes of colors on the landing page

### ISSUE THREAD

**Issue by Natashka333** [Together-100Devs/Together#336]
Another Figma file was created! It has a color palette with hex and RGB codes. Also, I put the landing page mockup next to the color palette and connected the arrows to the places where the specific colors go.  

https://www.figma.com/file/MhAf2jlXY8DU8qCszYTNZU/Color-palette?node-id=0%3A1&t=OoIn2Skt9kxatAeI-1

![Screen Shot 2023-02-16 at 5 14 17 PM](https://user-images.githubusercontent.com/102708144/219509248-28a45330-bf2b-4de2-90b4-a86a80d9df73.png)

**Comment by Illuztrado** [comment]
I'd like to work on this issue. I'm on Spongedude#6130 on Discord.

**Comment by Caleb-Cohen** [comment]
> I'd like to work on this issue. I'm on Spongedude#6130 on Discord.

All yours!

**Comment by Caleb-Cohen** [comment]
Hello @Illuztrado, just checking in on this thank ya!
