### ISSUE TITLE
Add a short delay when scrolling througth months.

### ISSUE THREAD

**Issue by intelagense** [Together-100Devs/Together#338]
## Please provide a summary of the feature
Currently, scrolling through the months is very sensitive and it is possible to scroll through the months very quickly and difficult to return to the current month. 

One solution might be able to change this behavior by adding short animations or a delay between months to slow down the scroll speed. Additionally, a bit of a buffer to the input before it starts scrolling could help prevent accidentally scrolling. Open to further suggestions or ideas. 

## Are there any potential issues you foresee with this feature
It is possible that animations would stack and still continue for every existing scroll input until caught up. 
Buffering input might be difficult due to the different ways that scrolling can happen. (pixel scrolling, line scrolling, touchscreen input, etc. )

## Is this feature related to any current or past issues? Please provide the #
Issue #238 and PR #301 added scrolling capability.
Completing #222 could serve as an interim fix to help a user get back to the current month after scrolling. 

## Which Branch should this fix be Pulled into?
PR into [branchName]

*If you're interested in working on this feature, please comment so you can be assigned*
Tagging @luciousmc in case you are interested in this one.

**Comment by luciousmc** [comment]
Yea I foresaw this coming up. If you use a track pad you can skip years lol. I can take this on.
