### ISSUE TITLE
Let's get rid of strokes and add some shading instead

### ISSUE THREAD

**Issue by Natashka333** [Together-100Devs/Together#346]
It is time to make some changes to the calendar page. 
The calendar buttons seem to have a better look without strokes. Also, adding shadows to buttons can make them more visually appealing and improve the user experience.
You can see the shadow settings in the screenshot. And it applies to all buttons.

![Screen Shot 2023-02-22 at 2 02 47 PM](https://user-images.githubusercontent.com/102708144/220747769-108e00b2-d2a2-447c-959c-c2453fdde694.png)

**Comment by luciousmc** [comment]
I can knock this out real quick since I created the components.
