### ISSUE TITLE
Add some colors to Sat and Sun

### ISSUE THREAD

**Issue by Natashka333** [Together-100Devs/Together#347]
Let's change the colors of Saturday and Sunday on the calendar to #E0835D (orange). It will make it easier for the users to differentiate the weekend from the rest of the week.

![Screen Shot 2023-02-22 at 2 05 52 PM](https://user-images.githubusercontent.com/102708144/220753306-73e23048-3ab6-44a6-b8a8-e626bdf811c8.png)

**Comment by ronthetech** [comment]
Hi, I would like to handle this issue, can it be assigned to me, or is further discussion needed?

**Comment by Natashka333** [comment]
> Hi, I would like to handle this issue, can it be assigned to me, or is further discussion needed?

Hi Ron! Cool! You are assigned.

**Comment by ronthetech** [comment]
Thanks!
