### ISSUE TITLE
Prevent event times from overlapping

### ISSUE THREAD

**Issue by sylfort** [Together-100Devs/Together#349]
## Describe the bug

The spans that tell the time for events are overlapping if there is a scrollbar in the container for events on one particular day.
 
## Expected behavior

The AM or PM text shouldn't be pushed to the next line. This can be achieved in a few different ways, the easiest would be using the tailwind class "whitespace-nowrap" but this then creates a horizontal scroll. 

A smaller font could also be used.

## Screenshots

![image](https://user-images.githubusercontent.com/24916160/221082744-ea0fe163-2ef2-40a8-afb2-827519902600.png)

## Which Branch should this fix be Pulled into?

PR into development

**Comment by Caleb-Cohen** [comment]
I'm not sure about the smaller font, but let's give it a try. We will be opening up an issue for expandable day cards which should remove the concern of horizontal scroll.
