### ISSUE TITLE
Add loading indicator

### ISSUE THREAD

**Issue by romanstetsyk** [Together-100Devs/Together#365]
## Please provide a summary of the feature

Sometimes it can take a while for all events to be fetched from the database. A loading indicator would be a nice feature.

## Additional context

![together](https://user-images.githubusercontent.com/25715951/222280277-3bb03233-dedc-4fc7-8244-0e7149b5440f.gif)

## Which Branch should this fix be Pulled into?

PR into `main`

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by Caleb-Cohen** [comment]
Great idea! 

what are your thoughts on loading events that are in the current month, visualizing, then loading events that are in prior and future months? I believe it should improve performance since most users are just looking at the current month anyways.

**Comment by Caleb-Cohen** [comment]
> I agree. Loading events for the current month is a good idea. When the user scrolls to another month, only then load more events. The performance will improve as the application grows and more events are created. Also, there's no need to load events from previous months automatically. In any case, having some sort of spinner or skeleton would be nice.

Yes I agree! I'll add an issue for loading.

**Comment by DevinCLane** [comment]
I'll take a look at this!

**Comment by jmoldyvan** [comment]
Would it be a different issue to try and find a solution to optimize loading all events?

**Comment by intelagense** [comment]
> Would it be a different issue to try and find a solution to optimize loading all events?

@jmoldyvan there is issue #366 which might be relevant

**Comment by intelagense** [comment]
https://user-images.githubusercontent.com/18331781/223742818-1eeb474f-1e60-48ba-b502-c3789b7ba142.mp4

I mocked up this "Shimmer" effect... it's a pretty common tactic. Something like this could go in the calendar day cards while waiting for the database to spool up. 

Were ya'll thinking of doing something like this or something more unique?

**Comment by DevinCLane** [comment]
I like this @intelagense

**Comment by DevinCLane** [comment]
good catch @intelagense, fixed it!
