### ISSUE TITLE
Fix Husky/Lint with Windows

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#367]
## Describe the bug

Husky/Lint/Prettier seems to have some conflict with Together unlike Mac and Linux. 7 Minute Dead commented on this [in discord](https://discord.com/channels/735923219315425401/1038482732633825442/1079093386281242805). I do not have a windows computer readily accessible so I require some assistance in diagnosing and resolving.

## Expected behavior

Lint/Husky/Prettier should function normally. 

## Screenshots

<img width="910" alt="Screenshot 2023-03-02 at 5 19 28 PM" src="https://user-images.githubusercontent.com/75268174/222585284-88404e6c-9db3-4ad2-9b24-22c0f6c38e0d.png">

## Which Branch should this fix be Pulled into?

PR into main

## Additional context

https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-eslint-delete-cr-prettier-prettier

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by code2244** [comment]
I will like to work on this issue.
