### ISSUE TITLE
Missing redirect when deleting events 

### ISSUE THREAD

**Issue by DevKnightRuin** [Together-100Devs/Together#374]
## Describe the bug
When deleting an event it doesn't redirect the page to show the changes

## To Reproduce

1. Delete and event and you an update until you refresh the page

## Expected behavior

When the modal closes, it should trigger a redirect on the page to refresh the calendar with the updated changes

## Which Branch should this fix be Pulled into?

Event modal dev branch would probably be best

**Comment by DevKnightRuin** [comment]
Updated issue, it was only on Delete

**Comment by r-Dev03** [comment]
Would it be okay if I try working on this? @Caleb-Cohen

**Comment by Caleb-Cohen** [comment]
> Would it be okay if I try working on this? @Caleb-Cohen 

Assigned!
