### ISSUE TITLE
Default startdate when adding event to specific day

### ISSUE THREAD

**Issue by timmyichen** [Together-100Devs/Together#377]
## Please provide a summary of the feature

Clicking on the + on a day should set the start date of the form to be that day

## Is this feature related to any current or past issues? Please provide the

Nope

## Additional context

N/A

## Which Branch should this fix be Pulled into?

Main

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by Caleb-Cohen** [comment]
I believe we already have this functionality.

**Comment by Illuztrado** [comment]
I'd like to work on this issue.
