### ISSUE TITLE
Mobile Burger Calendar Button Not Working

### ISSUE THREAD

**Issue by soph-em** [Together-100Devs/Together#389]
## Describe the bug

Tried to use Together calendar on mobile and was able to open burger bar, but none of the links other than the log-in button worked. 

## To Reproduce

1. Go to Together Calendar Home Page
2. Click on Burger Bar
3. Click 'calendar' button
4. Button does not work

## Expected behavior
Expected to go to calendar

## Which Branch should this fix be Pulled into?

PR into development

## Device Information

**Smartphone (please complete the following information):**

- Device: iphone 

## Additional context
Currently able to use calendar by making browser landscape and accessing desktop version. 

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by r-Dev03** [comment]
I would like to tackle this issue if that is ok.
