### ISSUE TITLE
Events repeated longer than 30 days add twice in the second month. 

### ISSUE THREAD

**Issue by ChuckTheBoss** [Together-100Devs/Together#401]
I created an event that repeats every Monday/Wednesday from Apr 6 - Jun 5. In the month of April, this event was added ONCE every Monday and Wednesday (correct; expected output) but in the months of May and June, each event was added TWICE (incorrect). 
![Screenshot 2023-04-06 at 3 26 07 PM](https://user-images.githubusercontent.com/105980393/230497056-1dad252a-ac71-4635-b792-4ae56bd878f5.png)
![Screenshot 2023-04-06 at 3 26 19 PM](https://user-images.githubusercontent.com/105980393/230497065-9cd8bc01-e03c-4953-9770-ccd43f3864a0.png)

**Comment by Caleb-Cohen** [comment]
Oof, good catch! Thanks for pointing that out!

**Comment by romanstetsyk** [comment]
Nice catch! This happens because when a recurring event is created, it is added to the database and to the state in React. When you switch to the next month, the same event is added to the state again.
I think I know how to fix it. @Caleb-Cohen should I create a new discussion or submit a pr directly?

**Comment by Caleb-Cohen** [comment]
> 

What would the discussion accomplish on this? PR sounds fine, depending on the previous question.

**Comment by Caleb-Cohen** [comment]
> Nice catch! This happens because when a recurring event is created, it is added to the database and to the state in React. When you switch to the next month, the same event is added to the state again.
> I think I know how to fix it. @Caleb-Cohen should I create a new discussion or submit a pr directly?

What would the discussion accomplish on this? PR sounds fine, depending on the previous question.
