### ISSUE TITLE
Add an API Endpoint that will return all events

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#406]
**Related Issues**
Project: Admin Dashboard
Depends on: 

**Description**
Add `getEventsForAdmin` method in the `events.js` controller that will return all events.

**Acceptance Criteria**
- API Endpoint returns all events
- Tests to confirm API enpoint exists and is functioning properly. This includes creating events, hitting API, and validating what was created is returned.

**Comment by Caleb-Cohen** [comment]
> I think I'd like to try my hand at this issue. But before I do, could I get some clarification on how this API endpoint should differ from the `getAll` method that already seems able to return all events?

that's a great question. It's been awhile since I checked this, but if memory serves me right, `getAll` only gets all the events for the current month, but I'll need to check that when I get home. *if* I'm wrong and `getAll` is truly a `getAll` then I'll need to adjust the ticket.

**Comment by Caleb-Cohen** [comment]
@cblanken

It looks like I was correct that `getAll` requires a date parameter.

```JS
  getAll(from, to) {
    return URL.get("/events", { params: { from, to } });
  }
```

Now, while I guess we could just pass in dates from the beginning of time to the end of time, I would still prefer a second endpoint. This is because we may want to change the endpoint to only pass back `pending` events at some point, additionally having the same endpoint for two entirely different functions seems abnormal.

I'm open to ideas if you disagree!

**Comment by cblanken** [comment]
I just realized the code snippet you posted was from `client/src/services/dataService.js`. Are those the endpoints I should be looking at or should it be the endpoints in `server/controllers/events.js`?

**Comment by Caleb-Cohen** [comment]
> I just realized the code you posted wasn't from `server/controllers/events.js`. What file is that code snippet from?

I pulled the last bit from the controller in events.js, the top bits are from the client side that calls the routes.

**Comment by cblanken** [comment]
> I pulled the last bit from the controller in events.js, the top bits are from the client side that calls the routes.

Oh I see. I didn't realize the quote wasn't all one file.

So do we still want to add a separate method (`getEventsForAdmin`) or would it make more sense to just call the current `getAll` method with no parameters from the frontend of the Admin Dashboard?

If I'm not mistaken it should return all events if the `from` and `to` parameters are left empty (`undefined`).

**Comment by Caleb-Cohen** [comment]
> > I pulled the last bit from the controller in events.js, the top bits are from the client side that calls the routes.
> 
> Oh I see. I didn't realize the quote wasn't all one file.
> 
> So do we still want to add a separate method (`getEventsForAdmin`) or would it make more sense to just call the current `getAll` method with no parameters from the frontend of the Admin Dashboard?
> 
> If I'm not mistaken it should return all events if the `from` and `to` parameters are left empty (`undefined`).

Let's use the getAll, we can re-open this ticket if we need a more specialized route in the future!

Thanks for looking into this and correcting my mistake!
