### ISSUE TITLE
Visualize all events returned from `getAll`

### ISSUE THREAD

**Issue by Caleb-Cohen** [Together-100Devs/Together#407]
**Related Issues**
Project: Admin Dashboard
Depends on: 
- #406 

**Description**
utilize `getAll` in DataService with an `undefined` date range
Visualize objects returned in `AdminDashboard.js`
Each visualized object should have event name, description, and author

**Acceptance Criteria**
Visualizes all events
Cypress testing to ensure it's visualized

**Comment by cblanken** [comment]
I'd like to jump on this issue now that we've closed #406

**Comment by Caleb-Cohen** [comment]
> I'd like to jump on this issue now that we've closed #406

All yours!

**Comment by Caleb-Cohen** [comment]
> I'd like to jump on this issue now that we've closed #406

PS. I updated the ticket to correctly reflect updates from #406

**Comment by cblanken** [comment]
Okay, I've added a visualization for events (see below), but currently I'm having issues generating more events while running the app in dev mode, so I'm still working on that to test a longer list of events.

Right now I've set up the page to load them when clicking the "Get All Events" button, but I'm assuming we'll want those to load automatically and I'll need to use something like `useEffect` to sync the data like how it's done in [Calendar.js](https://github.com/Together-100Devs/Together/blob/84361f3aaf3a6c324c52626918c07bc7dc29c20f/client/src/features/calendar/Calendar.js)? Just wanted to clarify before I dig into it more.

![image](https://github.com/Together-100Devs/Together/assets/19908880/72ab750f-8e30-4ac2-819d-0df0c14a30fd)

**Comment by Caleb-Cohen** [comment]
> Okay, I've added a visualization for events (see below), but currently I'm having issues generating more events while running the app in dev mode, so I'm still working on that to test a longer list of events.
> 
> Right now I've set up the page to load them when clicking the "Get All Events" button, but I'm assuming we'll want those to load automatically and I'll need to use something like `useEffect` to sync the data like how it's done in [Calendar.js](https://github.com/Together-100Devs/Together/blob/84361f3aaf3a6c324c52626918c07bc7dc29c20f/client/src/features/calendar/Calendar.js)? Just wanted to clarify before I dig into it more.
> 
> ![image](https://user-images.githubusercontent.com/19908880/253452432-72ab750f-8e30-4ac2-819d-0df0c14a30fd.png)

While I'm now familiar with other methods to accomplish this, let's keep the functionality the same for consistency.
