### ISSUE TITLE
Adding event with more than 280 chars sends 400 error on /events without UI feedback

### ISSUE THREAD

**Issue by nmpereira** [Together-100Devs/Together#417]
## Describe the bug

Adding event with description text longer than 280 chars sends a 400 error on /events post, but UI doesn't show any error

## To Reproduce

1. Go to https://together.cyclic.app/
2. Add event after logging in add a description with more than 280 characters
3. Add all other event details as usual (added non recurring - 2023-05-15 6.30pm to 7.30pm EST)
4. Submit event

## Expected behavior

Event is added

## Actual behavior
Modal says event is added successfully but debugging showed that the /events failed with a 400 error 

```
"\"description\" length must be less than or equal to 280 characters long"
```

## Screenshots

![chrome_xDfzAYiVSV](https://github.com/Together-100Devs/Together/assets/45009203/97262339-8dd8-467f-ad05-dafc31639a6c)

## Which Branch should this fix be Pulled into?

PR into [branchName]

## Device Information

**Desktop (please complete the following information):**

- OS: windows
- Browser : Chrome

## Additional context

Possible solutions:
1. remove the 280 char limit on the endpoint 
2. show user feedback that the event has not been added when there is a failed response
3. The HTML text box should limit the user from adding more than 280 chars

**Comment by Caleb-Cohen** [comment]
Thank ya for pointing this out!

**Comment by r-Dev03** [comment]
Would it be okay if I try working on this? @Caleb-Cohen
