### ISSUE TITLE
What is the license type?

### ISSUE THREAD

**Issue by KhuloodHassan** [Together-100Devs/Together#421]
## Summary of the suggested change
Add license type to the repo

## Link(s) to the documents to be changed
N/A

## Links to relevant resources
https://choosealicense.com/licenses/

## When you are finished:

- If this is an update to the Readme or Contributing.md, PR this into development.
- If this is an update to the Wiki, @ a maintainer so they can review your changes.

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by Caleb-Cohen** [comment]
Done!
