### ISSUE TITLE
Login and GitHub links on landing page are difficult to click.

### ISSUE THREAD

**Issue by intelagense** [Together-100Devs/Together#434]
## Describe the bug

The Login with Discord and the GitHub link on the landing page has the appearance of a button but only the text and logo area are clickable. 

## To Reproduce

1. Go to the Together landing page at https://together.cyclic.app/
(If you are redirected to the calendar view, click the Home button in the top left to go back to the landing page.)
2. Look at the login button on the top card and the GitHub repository link near the bottom of the page.
3. Hover a mouse cursor over the links.
(Alternatively, you can tab down to the links using keyboard shortcuts)
4. Notice that the link areas do not extend to the edges of their containers. 

## Expected behavior

The clickable link area should extend to the edge of the colored containers as they resemble buttons. 

## Screenshots
This is how the buttons look. 
![Together GitHub button](https://github.com/Together-100Devs/Together/assets/18331781/57bf47fe-84d2-4eab-b784-cddd7820d12a)
![Login button](https://github.com/Together-100Devs/Together/assets/18331781/3fa406bb-ad15-4ed1-9224-6d5678d3a88c)

Here are the current focusing rings. 
![Together GitHub button focus ring](https://github.com/Together-100Devs/Together/assets/18331781/ee6b66ad-c313-4352-ac03-c14f633ddc4c)
![Login with Discord focus ring](https://github.com/Together-100Devs/Together/assets/18331781/293f2e64-0fb8-4804-be70-7303a66ee423)

## Which Branch should this fix be Pulled into?

PR into main

## Device Information

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version Version 114.0.5735.199 (Official Build) (64-bit)
_Tested on my machine but likely affects all devices._ 

## Additional context

N/A

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by neeravbhaskarla** [comment]
Hi can I get it assigned?

**Comment by neeravbhaskarla** [comment]
Hi @intelagense Can I get this issue assigned to me?

**Comment by intelagense** [comment]
Sure!
Updated contributing docs are available in the wiki https://github.com/Together-100Devs/Together/wiki
Let me know if you need anything else.

**Comment by neeravbhaskarla** [comment]
Resolved this issue, raised a PR for this Issue. Please Check.

**Comment by neeravbhaskarla** [comment]
@intelagense Updated with new changes, Please check PR #436

**Comment by Caleb-Cohen** [comment]
closed great work @neeravbhaskarla!
