### ISSUE TITLE
When creating an event it's possible to bypass date validation on the front-end

### ISSUE THREAD

**Issue by romanstetsyk** [Together-100Devs/Together#443]
## Describe the bug

When creating an event it's possible to bypass date validation on the front-end.

## To Reproduce

1. Fill in the first two steps of the form 
2. Close the form
3. Click the 'plus' sign on any past dates to open the form
4. See the past date that shouldn't pass the validation

## Expected behavior

It shouldn't be possible to bypass form validation. One possible solution is to show plus button only for future days.

## Screenshots

https://github.com/Together-100Devs/Together/assets/25715951/0b3e3c71-3dfe-4556-9dec-e5d79d5ca888

## Which Branch should this fix be Pulled into?

PR into `main`

## Additional context

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by vguzman812** [comment]
Hi. I have implemented a fix for this that only displays the plus button on days that are >= current date. I would love to be assigned this. I will also initiate a pull request for this issue.
