### ISSUE TITLE
Creating events not working for events created in 2024

### ISSUE THREAD

**Issue by intelagense** [Together-100Devs/Together#454]
## Describe the bug

Users are unable to create new events this year. Although a message indicating the event has been successfully created is displayed to the user, the server actually responds with a 400 Error. As a result, the event is not created in the system.

## Steps to Reproduce:

Log in to the application.
Navigate to the event creation page.
Fill in the required event details and submit.
Expected Behavior: The event should be created successfully and stored in the server.

Actual Behavior: The user sees a confirmation message saying the event has been created. However, the server returns a 400 Error, and no event is actually created.

## Additional context

Likely related to server side event verification.

_If you're interested in working on this feature, please comment so you can be assigned_

**Comment by intelagense** [comment]
https://github.com/Together-100Devs/Together/blob/5285afa00a45b01764c7db8d3aef03286593f865/server/models/Event.js#L34

Ok I think it is just this.

**Comment by 20jasper** [comment]
@intelagense is this issue completed?

**Comment by intelagense** [comment]
@20jasper it is still being worked on. The code is good as far as I can tell but the site still needs some deployment tweaks to make the changes live.
